name: Deploy angular app to github page

on:
  push:
    branches:
      - main

permissions:
  contents: write

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 22.12

      - name: Install dependencies
        run: npm ci

      - name: Build Angular (force output path)
        run: |
          npm run build -- --configuration production \
          --output-path=dist/angularpoc \
          --base-href /angularpoc/

      # üîç DEBUG: show what Angular actually produced
      - name: List dist folder
        run: |
          echo "---- root ----"
          ls -la
          echo "---- dist ----"
          ls -la dist || true
          echo "---- dist/angularpoc ----"
          ls -la dist/angularpoc || true

      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v4
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_branch: gh-pages
          publish_dir: dist/angularpoc/browser
